### ISSUE TITLE
Add French name in /Items.json

### ISSUE THREAD

**Issue by Purukitto** [Purukitto/pokemon-data.json#7]
## **Description**
Add jname (Japanese name), cname (Chinese name (simplified)) and fname(Frech name) to [items.json](https://github.com/Purukitto/pokemon-data.json/blob/master/items.json) to make it consistent with the rest of the database.

#### From:
```
{
    "id": 1,
    "ename": "Master Ball",
    "type": "Pokeballs",
    "description": "The best Ball with the ultimate level of performance. It will catch any wild Pokémon without fail."
}
```

#### To:
```
{
    "id": 1,
    "name": {
        "english": "Master Ball",
        "japanese": "マスターボール",
        "chinese": "大师球",
        "french": "Master Ball"
    }
    "type": "Pokeballs",
    "description": "The best Ball with the ultimate level of performance. It will catch any wild Pokémon without fail."
}
```

## **Tasks :**
~- [ ] To add `jname`, `cname` and `fname`~
- [x] Change `name` structure 
- [x] To add `jname`
- [x] To add `cname`
- [ ] To add `fname`

### Comment below if you would like to claim this issue, please do not start working on the issue unless assigned to you explicitly

**Comment by Karim-Adnan** [comment]
I would like to contribute!

**Comment by Purukitto** [comment]
> I would like to contribute!

Sure go ahead

**Comment by Purukitto** [comment]
@Karim-Adnan Please refer to the updated structure

**Comment by Karim-Adnan** [comment]
alright

**Comment by Purukitto** [comment]
cname and jname already added, only french name left

**Comment by mintymelinda** [comment]
I can do this.
