### ISSUE TITLE
Change name structure in moves.json

### ISSUE THREAD

**Issue by Purukitto** [Purukitto/pokemon-data.json#8]
## **Description**
Change the name structure in [moves.json](https://github.com/Purukitto/pokemon-data.json/blob/master/moves.json) to be more in line with the upcoming update and to change the category from Chinese to English.

#### From:
```
{
        "accuracy": 100,
        "category": "物理",
        "cname": "拍击",
        "ename": "Pound",
        "id": 1,
        "jname": "はたく",
        "power": 40,
        "pp": 35,
        "type": "Normal"
    },
```

#### To:
```
{
		"id": 1,
		"name": {
        	"english": "Pound",
        	"japanese": "はたく",
        	"chinese": "拍击",
        	"french": "Écras’Face"
    	},
        "accuracy": 100,
        "power": 40,
        "pp": 35,
        "type": "Normal",
        "category": "Physical"
    },
```

## **Tasks :**
- [x] To nest `ename`, `jname` and `cname` under `name`
- [x] To add French name
- [x] To change the value of `category` from Chinese to English

### Comment below if you would like to claim this issue, please do not start working on the issue unless assigned to you explicitly

**Comment by rishavjaiss** [comment]
I can do this!

**Comment by Purukitto** [comment]
> I can do this!

Sure you can start working on it!

**Comment by rishavjaiss** [comment]
I'll make PR after 1st October during hacktoberfest. I hope that's okay.

**Comment by Purukitto** [comment]
> I'll make PR after 1st October during hacktoberfest. I hope that's okay.

I understand please start working on it and you can open the PR during hacktoberfest

**Comment by rishavjaiss** [comment]
Hey, I am completely new to this open source contribution thing. I didn't go through the repo and made a silly judgement on this upper given gist. I won't be able to give so much of time to this as the array length is huge. Please consider somebody else for this.
Sorry.

**Comment by Purukitto** [comment]
> Hey, I am completely new to this open source contribution thing. I didn't go through the repo and made a silly judgement on this upper given gist. I won't be able to give so much of time to this as the array length is huge. Please consider somebody else for this.
> Sorry.

It's okay in this specific case it was to be done by scraping data and by running scripts.
It's okay if you think you cant at this time!

**Comment by rishavjaiss** [comment]
Ya It needs to be automated and I think as of now I am not confident about it. Thanks for understanding!

**Comment by Digitl-Alchemyst** [comment]
I will look into finishing up reformatting the current data, looks like this is about half done in its current state. Id like to contribute to automatic scraping but that one will be an after thought.
